### ISSUE TITLE
Error at execution time

### ISSUE THREAD

**Issue by alexcamlo** [dev-sandman/slush-frontendless#2]
Install slush and slush-frontendless
When I slush frontendless this error shows.

> /usr/local/lib/node_modules/slush-frontendless/slushfile.js:123
>                   appLibraries:answers.appLibraries,
>                   ^^^^^^^^^^^^
> SyntaxError: Duplicate data property in object literal not allowed in strict mode
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Liftoff.handleArguments (/usr/local/lib/node_modules/slush/bin/slush.js:90:3)
>     at Liftoff.launch (/usr/local/lib/node_modules/slush/node_modules/liftoff/index.js:153:6)
>     at Object.<anonymous> (/usr/local/lib/node_modules/slush/bin/slush.js:57:5)

**Comment by radames-rex** [comment]
Sorry for the delay,
    you could send me the commands you used detail. I could not reproduce your error.

**Comment by alexcamlo** [comment]
This is what it shows when I slush frontendless at terminal

![screen shot 2016-02-10 at 20 20 45](https://cloud.githubusercontent.com/assets/121455/12958843/e575d99e-d033-11e5-88d6-fa39f177297c.png)

Tried also with sudo, just in case

![screen shot 2016-02-10 at 20 21 18](https://cloud.githubusercontent.com/assets/121455/12958845/e58e5be0-d033-11e5-8b76-fdd4694ead1d.png)

**Comment by radames-rex** [comment]
You installed the slush and slush-frontend using:
-> npm install -g slush
-> npm install -g slush-frontendless

Try reinstalling them

**Comment by alexcamlo** [comment]
I thing it was that my node and/or npm were outdated. Installed latest version and works now.

Thanks for your help and sorry for wasting your time.
